name: Upload yo google cloud VPS

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      -  uses: actions/checkout@v2

      -  name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v1
         with:
          node-version: ${{ matrix.node-version }}

      -  name: Login to GitHub Container Registry (ghcr)
         uses: docker/login-action@v2
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.TOKEN_PACKAGE_ACCESS }}

      -  name: Build and push docker image
         uses: docker/build-push-action@v2
         with:
           context: .
           push: true
           tags: ghcr.io/garedmx/example-cicd-integration:${{ github.ref_name }}

      -  name: Build and push docker image
         uses: docker/build-push-action@v2
         with:
           context: .
           push: true
           tags: ghcr.io/garedmx/example-cicd-integration:latest

      -  name: Run job jenkins
         run: |
           curl -X POST -H "Content-type: application/json" -H "Content-Length: 1000" -H "Authorization: Bearer 11c1587acdc8dcab5e40895e07d6e56aeb" "http://jenkins.corp.liveramp.com/generic-webhook-trigger/invoke"
          
